### ISSUE TITLE
请教如何实现通过华为SDK向群发所有人发送透传

### ISSUE THREAD

**Issue by yoshi315** [xuduo/socket.io-push#20]
您好，查阅了您的代码，并没有发现如果调用华为的群发所有人的透传，请指点

**Comment by xuduo** [comment]
只有通知走华为，小米。 HuaweiProvider 98行
透传不走。
透传和通知的区别在于，一个在线一个离线。
透传既然是在线，走我们内建通道，必然更可靠，延迟更低。
第三方（小米，华为）的接口调用成功率，不重试的情况下，大概只有99%左右。
