### ISSUE TITLE
ttlSchema的packets type

### ISSUE THREAD

**Issue by hcnode** [xuduo/socket.io-push#21]
我想提一个性能的问题
在ttlSchema里面定义的packets字段为字符串：
```javascript
      packets: {
        type: [String]
      },
```
type是否可以改成`Schema.Types.Mixed` ? 这样就不需要保存消息对象时候将json转换成string和发送消息时候又要将string转换成json，毕竟如果发送的量很大的话string和json之间转换会消耗cpu性能。

**Comment by xuduo** [comment]
是可以 ， 我mongodb不太熟， 已经改了
