### ISSUE TITLE
Redis服务器支持配置密码

### ISSUE THREAD

**Issue by kk17** [xuduo/socket.io-push#22]
Redis服务器支持配置密码，希望支持一下

**Comment by xuduo** [comment]
建议用iptable来控制访问， 由于目前还支持sentinel连接 这个改起来比较麻烦

**Comment by kk17** [comment]
我fork和修改了代码，但socket.io-push-redis要发布一个新版本，提了一个pull request，希望可以采纳

**Comment by kk17** [comment]
@xuduo socket.io-push-redis要发布一下新版本吧

**Comment by xuduo** [comment]
发布了0.8.84
