### ISSUE TITLE
Redis登录需要密码要怎么配置？

### ISSUE THREAD

**Issue by tangweihua** [xuduo/socket.io-push#24]
一般Redis都设置了密码的，对应的redis参数怎么写呢？

**Comment by xuduo** [comment]
用的 https://github.com/luin/ioredis

{
  port: 6379,          // Redis port
  host: '127.0.0.1',   // Redis host
  family: 4,           // 4 (IPv4) or 6 (IPv6)
  password: 'auth',
  db: 0
}

**Comment by tangweihua** [comment]
谢谢，那这个文件代码有点问题：
socket.io-push-redis/cluster.js -> getClientsFromIpList

**Comment by xuduo** [comment]
什么问题？

**Comment by tangweihua** [comment]
发现是用npm install时，socket.io-push-redis的版本问题。新版本其实已经支持密码了
