### ISSUE TITLE
npm 包有问题

### ISSUE THREAD

**Issue by Tang-RoseChild** [xuduo/socket.io-push#29]
版本号:0.8.99
问题: admin PushTest 页点击推送报错
![2017-09-22 10 13 52](https://user-images.githubusercontent.com/5513188/30726671-dd9ea66c-9f7e-11e7-81cf-91290ecccfdc.png)

原因:
发布的包中static/push/index.hmtl 文件和github上的不一致，多定义了pushAll。

**Comment by xuduo** [comment]
如果clone下的代码没问题，你可以尝试npm install socket.io-push@0.9.3
有些新的改动没有发到npm默认分支里

**Comment by Tang-RoseChild** [comment]
最好还是更新下吧，毕竟基本上都是通过npm来运行的

**Comment by xuduo** [comment]
已修复
