### ISSUE TITLE
push test 页发送数据的格式不对

### ISSUE THREAD

**Issue by Tang-RoseChild** [xuduo/socket.io-push#31]
版本号:0.8.99
问题: 
1.在PUSH Test 页面中输入聊天室内容```{"message":"2452","nickName":"wow","type":"chat_message"}```,topic 输入```chatRoom```，点击推送;
2.在聊天室中```https://localhost:12001/client/```会报错.

原因:
main.js initClient中
 ``` 
pushClient.on('push', function (data) {
            addChatMessage(data);
        })
```

收到的数据是string格式的，导致后面报错
说明发送的数据格式不对。

修改方案:
pull request :  [https://github.com/xuduo/socket.io-push/pull/30](https://github.com/xuduo/socket.io-push/pull/30)
将 data => 转换为Json ojb => 再转换为 json string

**Comment by xuduo** [comment]
原因是demo里transport写的不对， proxy多进程模式不支持polling
