### ISSUE TITLE
更新node-apn版本解决apn-http2 AssertionError

### ISSUE THREAD

**Issue by kk17** [xuduo/socket.io-push#36]
node-apn 2.1.4 以下的版本会出现apn-http2 AssertionError错误，所以需要更新到2.1.4及以上版本。具体问题见：[AssertionError: false == true in node-http2 lib/protocol/connection.js · Issue #471 · node-apn/node-apn](https://github.com/node-apn/node-apn/issues/471)

**Comment by xuduo** [comment]
这个问题你有遇到过吗？什么时候会出现

**Comment by kk17** [comment]
就是走apn通道推送的是时候会出现，node-apn的ticket上有相关讨论，看记录你以前也遇到过的呀
