### ISSUE TITLE
华为推送全部通知栏时报错

### ISSUE THREAD

**Issue by zhedoukeyihan** [xuduo/socket.io-push#38]
请求推送通知栏报错 result_code：80200001   huawei result_code pushtype is not valid
但是打印的请求参数pushtype是2  应该为正常，没有在华为推送文档里找到使用的该接口，是否此接口更新了所以报参数错误

**Comment by xuduo** [comment]
华为推送好像改了新接口，不支持全网推送了
我这需要接下新的才行

**Comment by zhedoukeyihan** [comment]
好的，麻烦了

**Comment by xlight** [comment]
期待华为能正常

**Comment by xuduo** [comment]
https://github.com/xuduo/socket.io-push/commit/58d7e4db97a6a585ecacae061ec66b6bebc6dca3

0.9.10 已经改为调用新接口 
旧版安卓sdk可以收到 杀进程收不到，可能需要更新客户端sdk才行

**Comment by zhedoukeyihan** [comment]
请问华为手机开启应用后注册的token是没有存吗还是获取的不对，拿不到用户对应的token数量一直是0，所以无法推送  打印：sendAll cursor end package_name 0

**Comment by xuduo** [comment]
看下客户端日志有没有成功获取token
