### ISSUE TITLE
Android push 到达率统计问题

### ISSUE THREAD

**Issue by sdmjhca** [xuduo/socket.io-push#40]
您好：
      我看你们是通过APP收到push消息后给服务器回包的方式统计到达率，我想问一下 APP收到通知栏消息后，APP是如何给服务器回包的，有没有相关的demo可以参考

**Comment by xuduo** [comment]
下发的通知带个id，时间戳，客户端收到，回复这个id和时间戳，可以计算出是否收到和延迟

**Comment by sdmjhca** [comment]
多谢您的回复，APP是通过socket给服务器进行回复？如果是的话 此时APP应该是离线状态，你们是接受到通知后又新建了一个socket连接 进行回包？

**Comment by xuduo** [comment]
走自己通道的，用原socket回复，其它厂商之类的是其它统计方法，你可以研究下代码

**Comment by sdmjhca** [comment]
好的多谢 我还以为第三方的也可以通过APP回包 看来还是不行

**Comment by xuduo** [comment]
第三方友盟可以，会拉起你进程，小米有提供trace接口 查询送达。apn调用的时候有返回是否成功
